import mongoose from "mongoose";

const user = new mongoose.Schema({
    id: {type: String, require: true, unique: true},
    name: {type: String, default: ''},
    title: {type: String, default: ''},
    email: {type: String, default: ''},
    gender: {type: String, default: ''},
    veh_no: {type: String, default: ''},
    income: {type: Number, default: 0},
    expense: {type: Number, default: 0},
    accum_score: {type: Number, default: 0},
    rideshare: {
        no: {type: String},  // rideshare no
        status: {type: Number}, // definition?
    },
    reservation: {
        no: {type: String},  // reservation no
        status: {type: Number}, // definition?
    },
    history: {
        rideshare: [String],    // rideshare no
        reservation: [String],  // reservation no
    }
    // rating: {type:[Number], default: [0, 0, 0, 0, 0]},  // drv rating list
}, {_id: false});

const reservation = mongoose.Schema({
    // frontend
    no: {type: String, require: true},  // generated by backend
    veh_no: {type: String, require: true},
    drv_name: {type: String, require: true},
    date: {type: {
        year: {type: Number, require: true},
        month: {type: Number, require: true},
        day: {type: Number, require: true},
        // weekday: {type: Number, require: true},
    }, require: true, _id : false},
    dep: {type: {
        stop: {type: String, require: true},
        hour: {type: Number, require: true},
        minute: {type: Number, require: true},
    },require: true, _id : false},
    arr: {type: {
        stop: {type: String, require: true},
        hour: {type: Number, require: true},
        minute: {type: Number, require: true},
    },require: true, _id : false},
    fare: {type: Number, require: true},

    // backend
    rideshare: {type: String, require: true},   // rideshare no
    pax_id: {type: String, require: true},
    dep_idx: {type: Number, require: true},
    arr_idx: {type: Number, require: true},
}, {_id: false});

reservation.index({no: 1, date: 1}, {unique: true});

const rideshare = new mongoose.Schema({
    // frontend
    no: {type: String, require: true},    // generated by backend
    price: {type: Number, require: true},
    veh_no: {type: String, require: true},
    drv_name: {type: String, require: true},
    drv_rating: {type: Number, require: true},
    capacity: {type: Number, require: true},
    date: {type: {
        year: {type: Number, require: true},
        month: {type: Number, require: true},
        day: {type: Number, require: true},
        // weekday: {type: Number, require: false},
    }, require: true, _id : false},
    schedule:{type: [{
        stop: {type: String, require: true},
        hour: {type: Number, require: true},
        minute: {type: Number, require: true},
        accum_fare: {type: Number, require: true},
        volume: {type: Number, default: 0},
    }], required: true, _id : false},

    // backend
    drv_id: {type: String, require: true},
    reservation: {type: [String], default: []}   // reservation no
},{_id: false});

rideshare.index({no: 1, date: 1}, {unique: true});

export default {
    user,
    rideshare,
    reservation,
}